name: Publish NuGet Package

on:
  push:
    branches:
      - main

  # Optionally, you can add a trigger for creating a new release:
  # release:
  #   types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/Piri.sln

      - name: Build the project
        run: dotnet build src/Piri.sln --configuration Release --no-restore

      - name: Pack the NuGet package
        run: dotnet pack src/Piri.sln --configuration Release --no-restore --output ./nupkg

      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "./nupkg/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
